export { default as FolderOutlinedIcon } from '@mui/icons-material/FolderOutlined'
export { default as FolderOpenOutlinedIcon } from '@mui/icons-material/FolderOpenOutlined'
export { default as ExpandLessIcon } from '@mui/icons-material/ExpandLess'
export { default as ChevronRightOutlinedIcon } from '@mui/icons-material/ChevronRightOutlined'
export { default as ChevronLeftOutlinedIcon } from '@mui/icons-material/ChevronLeftOutlined'
export { default as HistoryOutlinedIcon } from '@mui/icons-material/HistoryOutlined'
export { default as WidgetsOutlinedIcon } from '@mui/icons-material/WidgetsOutlined'
