export enum ActivityOperation {
  // MODEL_RUN
  LAYOUT_IDENTIFICATION = 'LAYOUT_IDENTIFICATION',
  IMAGE_ENHANCEMENT = 'IMAGE_ENHANCEMENT',
  OCR = 'OCR',
  POST_OCR_CORRECTION = 'POST_OCR_CORRECTION',
  // Image-level manual ops
  ROTATE = 'ROTATE',
  CROP = 'CROP',
  BRIGHTNESS_ADJUST = 'BRIGHTNESS_ADJUST',
  CONTRAST_ADJUST = 'CONTRAST_ADJUST',
  SHARPNESS_ADJUST = 'SHARPNESS_ADJUST',
  PDF_SPLIT = 'PDF_SPLIT',
  // Segment-level manual ops
  SEGMENT_ADD = 'SEGMENT_ADD',
  SEGMENT_RESHAPE = 'SEGMENT_RESHAPE',
  SEGMENT_DELETE = 'SEGMENT_DELETE',
  SEGMENT_LABEL_CHANGE = 'SEGMENT_LABEL_CHANGE',
  SEGMENT_REORDER = 'SEGMENT_REORDER',
  SEGMENT_REVERT = 'SEGMENT_REVERT',
  SEGMENTS_CROP = 'SEGMENTS_CROP',
  // OCR text edits
  OCR_TEXT_EDIT = 'OCR_TEXT_EDIT',
  POST_OCR_TEXT_EDIT = 'POST_OCR_TEXT_EDIT',
  // Reverts
  LAYOUT_IDENTIFICATION_REVERT = 'LAYOUT_IDENTIFICATION_REVERT',
  IMAGE_ENHANCEMENT_REVERT = 'IMAGE_ENHANCEMENT_REVERT',
  OCR_REVERT = 'OCR_REVERT',
  POST_OCR_REVERT = 'POST_OCR_REVERT',
  FILE_RESET = 'FILE_RESET',
}
