import type { ImageAnnotation } from '@annotorious/react'
import React from 'react'

// Re-export ImageAnnotation for convenience
export type { ImageAnnotation }

// ============================================================================
// Simple Annotation Types - User-friendly format
// ============================================================================

/** Rectangle bounds in simple format */
export type AnnotationBounds = {
  x: number
  y: number
  width: number
  height: number
}

/** Simple annotation format - easy to use and understand */
export type SimpleAnnotation = {
  /** Unique identifier (auto-generated if not provided) */
  id?: string
  /** Label/tag for the annotation */
  label: string
  /** Label type classification (e.g. text, non-text) */
  labelType?: string | null
  /** Detection confidence score (0-1) */
  confidence?: number
  /** Rectangle bounds of the annotation */
  bounds: AnnotationBounds
  /** Source of the annotation */
  type?: 'GENERATED' | 'MANUAL'
  /** Model run id when the annotation was generated by a model run; undefined for manual */
  modelRunId?: string | null
}

// ============================================================================
// Drawing & Style Types
// ============================================================================

export type DrawingTool = 'rectangle' | 'polygon'

export type AnnotationStyle = {
  fill?: string
  fillOpacity?: number
  stroke?: string
  strokeWidth?: number
}

/** Style function type for custom annotation styling */
export type AnnotationStyleFunction = (
  annotation: ImageAnnotation,
  index: number
) => AnnotationStyle

// ============================================================================
// Label Types
// ============================================================================

/** Label position relative to annotation bounds */
export type LabelPosition =
  | 'top'
  | 'bottom'
  | 'inside'
  | 'top-left'
  | 'top-right'

/** Label style configuration */
export type LabelStyleConfig = {
  /** Font size in pixels */
  fontSize?: number
  /** Font weight */
  fontWeight?: 'normal' | 'bold' | number
  /** Text color */
  color?: string
  /** Background color */
  backgroundColor?: string
  /** Padding in pixels */
  padding?: number
  /** Border radius in pixels */
  borderRadius?: number
  /** Position of the label */
  position?: LabelPosition
  /** Maximum width before text truncation */
  maxWidth?: number
}

// ============================================================================
// Component Props
// ============================================================================

export type ImageAnnotatorProps = {
  /** Image source URL */
  src: string
  /** Alt text for the image */
  alt?: string
  /** Initial annotations in simple format (label + bounds) */
  annotations?: SimpleAnnotation[]
  /** Currently active drawing tool */
  tool?: DrawingTool
  /** Enable or disable drawing */
  drawingEnabled?: boolean
  /** Custom annotation style */
  style?: AnnotationStyle
  /** Custom color palette */
  colorPalette?: string[]
  /** Fill opacity for annotations (0-1) */
  fillOpacity?: number
  /** Stroke width for annotations */
  strokeWidth?: number
  /** Custom style function for full control over annotation styling */
  styleFunction?: AnnotationStyleFunction
  /** Show labels on annotations */
  showLabels?: boolean
  /** Label style configuration */
  labelStyle?: LabelStyleConfig
  /** CSS class for the image element */
  imageClassName?: string
  /** CSS class for the container */
  containerClassName?: string
  /** Callback when annotation is created (simple format) */
  onAnnotationCreate?: (annotation: SimpleAnnotation) => void
  /** Callback when annotation is updated (simple format) */
  onAnnotationUpdate?: (
    annotation: SimpleAnnotation,
    previous: SimpleAnnotation
  ) => void
  /** Callback when annotation is deleted (simple format) */
  onAnnotationDelete?: (annotation: SimpleAnnotation) => void
  /** Callback when annotations change (simple format, debounced) */
  onAnnotationsChange?: (annotations: SimpleAnnotation[]) => void
  /** Callback when annotation is selected (simple format) */
  onAnnotationSelect?: (annotation: SimpleAnnotation | null) => void
  /** ID of the annotation to programmatically select */
  selectedAnnotationId?: string | null
  /** Callback when annotation label is edited */
  onLabelEdit?: (annotation: SimpleAnnotation, newLabel: string) => void
  /** Callback when annotation label type is changed */
  onLabelTypeChange?: (
    annotation: SimpleAnnotation,
    newLabelType: string
  ) => void
  /** Enable label editing on click */
  editable?: boolean
  /** Click handler for the image */
  onClick?: (e: React.MouseEvent) => void
  /** Debounce time for annotations change callback (ms) */
  debounce?: number
  // Zoom, Pan & Fullscreen options
  /** Enable zoom functionality (default: false) */
  zoomEnabled?: boolean
  /** Zoom configuration */
  zoomConfig?: ZoomConfig
  /** Enable pan when zoomed (default: true when zoomEnabled) */
  panEnabled?: boolean
  /** Enable fullscreen functionality (default: false) */
  fullscreenEnabled?: boolean
  /** Zoom toolbar configuration */
  toolbar?: ZoomToolbarConfig
  /** Callback when zoom level changes */
  onZoomChange?: (state: ZoomState) => void
  /** Callback when fullscreen state changes */
  onFullscreenChange?: (isFullscreen: boolean) => void
  /** If Custom Icon for Zoom in is needed */
  zoomInCustomIcon?: React.ReactNode
  /** If Custom Icon for Zoom out is needed */
  zoomOutCustomIcon?: React.ReactNode
  /** If Custom Icon for Reset is needed */
  resetCustomIcon?: React.ReactNode
  /** If Custom Icon for Fullscreen is needed */
  fullscreenCustomIcon?: React.ReactNode
}

// ============================================================================
// Internal Types
// ============================================================================

/** Event handler types for Annotorious */
export type AnnotationEventHandler = (annotation: ImageAnnotation) => void
export type AnnotationUpdateHandler = (
  annotation: ImageAnnotation,
  previous: ImageAnnotation
) => void
export type SelectionHandler = (annotations: ImageAnnotation[]) => void

/** Annotorious instance type with methods we use */
export interface AnnotatorInstance {
  on(event: 'createAnnotation', handler: AnnotationEventHandler): void
  on(event: 'updateAnnotation', handler: AnnotationUpdateHandler): void
  on(event: 'deleteAnnotation', handler: AnnotationEventHandler): void
  on(event: 'selectionChanged', handler: SelectionHandler): void
  off(event: 'createAnnotation', handler: AnnotationEventHandler): void
  off(event: 'updateAnnotation', handler: AnnotationUpdateHandler): void
  off(event: 'deleteAnnotation', handler: AnnotationEventHandler): void
  off(event: 'selectionChanged', handler: SelectionHandler): void
  addAnnotation: (annotation: ImageAnnotation) => void
  updateAnnotation: (annotation: ImageAnnotation) => void
  removeAnnotation: (annotationId: string) => void
  clearAnnotations: () => void
  setAnnotations: (annotations: ImageAnnotation[], replace?: boolean) => void
  setDrawingTool: (tool: string) => void
  setDrawingEnabled: (enabled: boolean) => void
  setSelected: (id?: string) => void
}

/** Internal props for AnnotatorContent */
export type AnnotatorContentProps = Omit<ImageAnnotatorProps, 'annotations'> & {
  initialAnnotations?: ImageAnnotation[]
  /** Current zoom level for label scaling (passed from parent) */
  currentZoom?: number
}

/** Props for single annotation label */
export type AnnotationLabelProps = {
  annotation: SimpleAnnotation
  style: Required<LabelStyleConfig>
  color?: string
  scale: number
  editable?: boolean
  isEditing?: boolean
  onStartEdit?: () => void
  onSaveEdit?: (newLabel: string) => void
  onCancelEdit?: () => void
  onDelete?: () => void
  onLabelTypeChange?: (newType: string) => void
}

/** Props for annotation labels overlay */
export type AnnotationLabelsOverlayProps = {
  annotations: SimpleAnnotation[]
  labelStyle: Required<LabelStyleConfig>
  containerRef: React.RefObject<HTMLDivElement | null>
  editable?: boolean
  onLabelEdit?: (annotation: SimpleAnnotation, newLabel: string) => void
  onDelete?: (annotation: SimpleAnnotation) => void
  onLabelTypeChange?: (annotation: SimpleAnnotation, newType: string) => void
  /** Current zoom level for proper label positioning */
  currentZoom?: number
}

// ============================================================================
// Zoom, Pan & Fullscreen Types
// ============================================================================

/** Zoom configuration */
export type ZoomConfig = {
  /** Minimum zoom level (default: 0.5) */
  minZoom?: number
  /** Maximum zoom level (default: 5) */
  maxZoom?: number
  /** Zoom step for each zoom in/out action (default: 0.25) */
  zoomStep?: number
  /** Enable mouse wheel zoom with Ctrl/Cmd (default: true) */
  wheelZoom?: boolean
  /** Enable pinch-to-zoom on touch devices (default: true) */
  pinchZoom?: boolean
}

/** Toolbar configuration for zoom controls */
export type ZoomToolbarConfig = {
  /** Show the toolbar (default: false) */
  show?: boolean
  /** Position of the toolbar (default: 'top-right') */
  position?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'
  /** Show zoom in button (default: true) */
  showZoomIn?: boolean
  /** Show zoom out button (default: true) */
  showZoomOut?: boolean
  /** Show reset zoom button (default: true) */
  showReset?: boolean
  /** Show fullscreen button (default: true) */
  showFullscreen?: boolean
  /** Show zoom level indicator (default: true) */
  showZoomLevel?: boolean
  /** Show pan/move mode toggle button (default: true) */
  showPanToggle?: boolean
}

/** Current zoom/pan state */
export type ZoomState = {
  /** Current zoom level (1 = 100%) */
  zoom: number
  /** Pan offset X in pixels */
  panX: number
  /** Pan offset Y in pixels */
  panY: number
}

/** Ref handle for external control of zoom/pan/fullscreen */
export type ImageAnnotatorHandle = {
  /** Zoom in by one step */
  zoomIn: () => void
  /** Zoom out by one step */
  zoomOut: () => void
  /** Set zoom to a specific level */
  setZoom: (level: number) => void
  /** Reset zoom to 1 and center the image */
  resetZoom: () => void
  /** Toggle fullscreen mode */
  toggleFullscreen: () => void
  /** Get current zoom state */
  getZoomState: () => ZoomState
}
